bin: use fakeroot to ensure files owner is root
fallback to docker if fakeroot not found on host

diff --git a/bin/ipk2apk b/bin/ipk2apk
--- a/bin/ipk2apk
+++ b/bin/ipk2apk
@@ -204,7 +204,7 @@ EOF
         extra_args+=(--info "tags:openwrt:cpe=$pkg_cpe_id")
     fi
 
-    apk mkpkg \
+    fakeroot apk mkpkg \
         --info "name:$pkg_name" \
         --info "version:$pkg_version" \
         --info "description:$pkg_desc" \
@@ -238,8 +238,8 @@ script_dir() {
 }
 
 fallback_to_docker_if_needed() {
-	[ -z "$(which apk)" ] || return 0
-	echo "apk command not found in PATH, fallback to docker apk command"
+	[ -z "$(which apk)" -o -z "$(which fakeroot)" ] || return 0
+	echo "apk or fakeroot command not found in PATH, fallback to docker"
 	local docker_fake_root="$(readlink -f "$(script_dir)/../docker")"
 	"$docker_fake_root/init.sh" "$1" || { echo "docker fallback path failed!"; exit 1; }
 	export PATH="$docker_fake_root/bin:$PATH"
